[tool]
[tool.poetry]
name = "FlashUserbot_Deployer"
version = "1.0"
description = "Automatic Deploy FlashUserBot to Heroku"
authors = ["Flash"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
